objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Birthday__c</fullName>
        <label>Birthday</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Department__c</fullName>
        <label>IT Department</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>QA</fullName>
                </value>
                <value>
                    <fullName>DEV</fullName>
                </value>
                <value>
                    <fullName>PMO</fullName>
                </value>
                <value>
                    <fullName>BA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Level</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Employee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EmployeeSkill__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Time__c</fullName>
        <label>Assigned Time</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Employee Skills</relationshipLabel>
        <relationshipName>EmployeeSkills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Developer</fullName>
                </value>
                <value>
                    <fullName>Tester</fullName>
                </value>
                <value>
                    <fullName>Team Lead</fullName>
                </value>
                <value>
                    <fullName>Project Manager</fullName>
                </value>
                <value>
                    <fullName>Project Owner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Employee Skills r</relationshipLabel>
        <relationshipName>EmployeeSkills</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>EmployeeSkill</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>EmployeeSkills Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EmployeeSkills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hot</fullName>
                </value>
                <value>
                    <fullName>Hight</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Level.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Junior</fullName>
    </customValue>
    <customValue>
        <fullName>Middle</fullName>
    </customValue>
    <customValue>
        <fullName>Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Architector</fullName>
    </customValue>
    <masterLabel>Level</masterLabel>
</GlobalValueSet>

classes/L_EmployeeControllerTest.cls
@isTest
private class L_EmployeeControllerTest {



	@testSetup static void setup() {
		Employee__c employee = new Employee__c(	First_Name__c = 'TestF', Last_Name__c='TestL', 
			Birthday__c=system.today(), IT_Department__c='QA', Level__c='Junior', 	
			Start_Date__c=system.today(), isActive__c= true
		);
		Employee__c employee2 = new Employee__c(	First_Name__c = 'TestF2', Last_Name__c='TestL2', 
			Birthday__c=system.today(), IT_Department__c='DEV', Level__c='Junior', 	
			Start_Date__c=system.today(), isActive__c= true
		);
		List<Employee__c> employees = new List<Employee__c>();
		employees.add(employee);
		employees.add(employee2);

		insert employees;


		// Account acc = new Account(Name = 'Test');
		// insert acc; 

		// Project__c project = new Project__c(
		// 	Name = 'Test', 	Start_Date__c = system.today(), Priority__c = 'Hot', Account__c = acc.Id
		// );
		// insert project;

		// EmployeeSkill__c skill1 = new EmployeeSkill__c(
		// 	Position__c = 'Tester', Assigned_Time__c=6.0, Employee__c = employee.Id,
		// 	Project__c = project.Id
		// );
		// insert skill1;
	}




	
	@isTest static void testGetPicklistValues() {
		List<String> pickListValues = new List<String>();
		pickListValues = L_EmployeeController.getPicklistValues('Employee__c', 'IT_Department__c');

		System.assert(pickListValues.size() > 0);

	}

	@isTest static void testGetPicklistValuesNullPointerExcep() {
		List<String> pickListValues = new List<String>();
		pickListValues = L_EmployeeController.getPicklistValues('ERROREmployee__c', 'IT_Department__c');

		System.assertEquals(1, L_EmployeeController.forTest);

	}


	@isTest static void testGetFilteredEmployees() {
		List<L_EmployeeController.WrappEmployee> wEmpls = L_EmployeeController.getFilteredEmployees('','','');
		System.assertEquals(2, wEmpls.size());

		List<L_EmployeeController.WrappEmployee> wEmpls2 = L_EmployeeController.getFilteredEmployees('TestF2','','');
		System.assertEquals(1, wEmpls2.size());

		List<L_EmployeeController.WrappEmployee> wEmpls3 = L_EmployeeController.getFilteredEmployees('TestF2','DEV','');
		System.assertEquals(1, wEmpls3.size());

		List<L_EmployeeController.WrappEmployee> wEmpls4 = L_EmployeeController.getFilteredEmployees('TestF2','DEV','Junior');
		System.assertEquals(1, wEmpls4.size());

	}
	

	
}