objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Employee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EmployeeSkill__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Employee Skills</relationshipLabel>
        <relationshipName>EmployeeSkills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Employee Skills r</relationshipLabel>
        <relationshipName>EmployeeSkills</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>EmployeeSkill</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>EmployeeSkills Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EmployeeSkills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Owner</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Projects Owner</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Members__c</fullName>
        <label>Team Members</label>
        <summaryForeignKey>EmployeeSkill__c.Project__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/L_AccountProjectController.cls
public class L_AccountProjectController {

    @AuraEnabled
    public static String getAccountsWithProject() {

        if (!Schema.getGlobalDescribe().get('Account').getDescribe().isAccessible()
                || !Schema.getGlobalDescribe().get('Project__c').getDescribe().isAccessible()) {
            throw new AuraHandledException('Access error');
        }

        Account[] accountWithProjectsList = [
                SELECT id, Name, (
                        SELECT id, Name, Team_Members__c
                        FROM Projects__r
                )
                FROM Account
                WHERE Id IN (SELECT Account__c FROM Project__c)
                ORDER BY Name
                LIMIT 20
        ];
        List<AccountWithProjectsWrapper> AccountWithProjectWrapperList = formAccountWithProjectsWrapper(accountWithProjectsList);
        return JSON.serialize(AccountWithProjectWrapperList);
    }

    @AuraEnabled
    public static String getAccountProjects(Id accountId) {

        if (!Schema.getGlobalDescribe().get('Account').getDescribe().isAccessible()
                || !Schema.getGlobalDescribe().get('Project__c').getDescribe().isAccessible()) {
            throw new AuraHandledException('Access error');
        }

        Account[] accountWithProjectsList;
        try {
            accountWithProjectsList = [
                    SELECT Id,Name, (
                            SELECT id,Name
                            FROM Projects__r
                    )
                    FROM Account
                    WHERE Id = :accountId
            ];
        } catch (DmlException e) {
            throw new AuraHandledException('You try to break us');
        }
        List<AccountWithProjectsWrapper> AccountWithProjectWrapperList = formAccountWithProjectsWrapper(accountWithProjectsList);
        return JSON.serialize(AccountWithProjectWrapperList);
    }

    private static List<AccountWithProjectsWrapper> formAccountWithProjectsWrapper(List<Account> accountWithProjectsList) {

        Map<Id, AccountWithProjectsWrapper> accountWithProjectsWrapperMap = new Map<Id, L_AccountProjectController.AccountWithProjectsWrapper>();
        Map<Id, AccountProjects> AccountProjectsWrapperMap = new Map<Id, L_AccountProjectController.AccountProjects>();
        List<Id> projectIdList = new List<Id>();
        Map<Id, List<Id>> projectIdEmployeeIdMap = new Map<Id, List<Id>>();

        for (Account accountWithProjects : accountWithProjectsList) {

            AccountWithProjectsWrapper account = new AccountWithProjectsWrapper();
            account.accountId = accountWithProjects.Id;
            account.accountName = accountWithProjects.Name;
            accountWithProjectsWrapperMap.put(accountWithProjects.Id, account);

            for (Project__c project : (Project__c[]) accountWithProjects.Projects__r) {

                AccountProjects accountProject = new AccountProjects();
                accountProject.projectId = project.Id;
                accountProject.projectName = project.Name;
                accountProject.accountId = accountWithProjects.Id;
                AccountProjectsWrapperMap.put(project.Id, accountProject);
                projectIdList.add(project.Id);
            }
        }

        List<AggregateResult> employeeCount = [
                SELECT project__c, COUNT_DISTINCT(Employee__c) employeeCount
                FROM EmployeeSkill__c
                WHERE project__c IN :projectIdList AND Employee__R.isActive__c = true
                GROUP BY project__c
        ];

        AggregateResult[] projectAndEmployeeId = [SELECT employee__c,project__c from EmployeeSkill__c where project__c IN :projectIdList group By employee__c, project__c];
        for (AggregateResult projectWithEmployeeId : projectAndEmployeeId) {
            Id projectId = (id) projectWithEmployeeId.get('project__c');
            Id employeeId = (id) projectWithEmployeeId.get('employee__c');
            if (!projectIdEmployeeIdMap.containsKey(projectId)) {
                List<Id> employeeIdsList = new List<Id>();
                employeeIdsList.add(employeeId);
                projectIdEmployeeIdMap.put(projectId, employeeIdsList);
            } else {
                projectIdEmployeeIdMap.get(projectId).add(employeeId);
            }
        }
        for (AggregateResult countEmployeeOnProject : employeeCount) {
            Id projectId = (Id) countEmployeeOnProject.get('project__c');
            AccountProjects accountProject = AccountProjectsWrapperMap.get(projectId);
            accountProject.teamMembers = (Integer) countEmployeeOnProject.get('employeeCount');
            accountProject.employeeIds = projectIdEmployeeIdMap.get(projectId);
        }
        for (AccountProjects project : AccountProjectsWrapperMap.values()) {
            System.debug(project);
            AccountWithProjectsWrapper account = accountWithProjectsWrapperMap.get(project.accountId);
            if (account.accountProjects == null) {
                List<AccountProjects> accountProject = new List<AccountProjects>();
                accountProject.add(project);
                account.accountProjects = accountProject;
            } else {
                account.accountProjects.add(project);
            }
        }

        return accountWithProjectsWrapperMap.values();
    }

    public class AccountWithProjectsWrapper {
        public String accountName { get; set; }
        public Id accountId { get; set; }
        public AccountProjects[] accountProjects { get; set; }
    }

    public class AccountProjects {
        public Id projectId { get; set; }
        public String projectName { get; set; }
        public Integer teamMembers { get; set; }
        public List<Id> employeeIds { get; set; }
        public Id accountId;
    }
}